name: Test

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 8.x
          java-package: jre
          architecture: x64

      - name: Setup Rust
        uses: actions-rs/cargo@v1

      - name: git clone
        uses: actions/checkout@v2

      - name: Test
        run: make
